# Generated by Django 5.1.1 on 2024-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_team_alter_character_options_alter_character_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(verbose_name='Название команды'),
        ),
    ]
