# Generated by Django 5.1.1 on 2024-10-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_position_character_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Способность')),
            ],
            options={
                'verbose_name': 'Способность',
                'verbose_name_plural': 'Способности',
            },
        ),
    ]
