# Generated by Django 5.1.1 on 2024-10-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_character_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Тип медиа')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.TextField(verbose_name='Позиция на поле'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.TextField(verbose_name='Название эпизода')),
                ('episode', models.IntegerField(verbose_name='Номер эпизода')),
                ('volume', models.IntegerField(verbose_name='Номер раздела')),
                ('description', models.TextField(verbose_name='Описание эпизода')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.contenttype')),
            ],
        ),
    ]
