# Generated by Django 5.1.1 on 2024-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_character_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='picture',
            field=models.ImageField(null=True, upload_to='characters', verbose_name='Изображение'),
        ),
    ]
