# Generated by Django 5.1.1 on 2025-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(verbose_name='Полное имя'),
        ),
    ]
