# Generated by Django 5.1.1 on 2025-12-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(null=True, verbose_name='Полное имя'),
        ),
    ]
