# Generated by Django 5.1.1 on 2024-10-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_contenttype_alter_position_name_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
    ]
