# Generated by Django 5.1.1 on 2024-10-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Тип контента', 'verbose_name_plural': 'Типы контента'},
        ),
    ]
