# Generated by Django 5.1.1 on 2024-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_alter_contenttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание способности'),
        ),
    ]
